# Generated by Django 4.2.13 on 2024-06-09 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_artproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artproject',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artproject',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artproject',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
