# Generated by Django 4.2.13 on 2024-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0005_artproject_end_date_artproject_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
