# Generated by Django 4.2.13 on 2024-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0006_alter_artproject_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artproject',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media_manager.tag'),
        ),
    ]
