# Generated by Django 4.2.13 on 2024-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0007_tag_artproject_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artproject',
            name='technologies',
        ),
    ]
