# Generated by Django 4.2.13 on 2024-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0009_tag_color_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HennaDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='henna_designs/')),
                ('is_video', models.BooleanField(default=False)),
            ],
        ),
    ]
