# Generated by Django 4.2.13 on 2024-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0010_hennadesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hennadesign',
            name='file',
        ),
        migrations.AddField(
            model_name='hennadesign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hennadesign',
            name='video',
            field=models.FileField(blank=True, upload_to='henna_designs/'),
        ),
    ]
