# Generated by Django 4.2.13 on 2024-06-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0011_remove_hennadesign_file_hennadesign_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hennadesign',
            old_name='video',
            new_name='file',
        ),
    ]
